@startuml
(*)  --> "onCreate"
left to right direction
--> "checkLocationPermission"
--> "updateValuesFromBundle"
--> "onStart"
--> "onResume"
--> "onPause"
--> "onMapReady"
--> "DownloadKMLfile"
--> "onSaveInstanceState"
--> "onPostExecute"
--> "onRequestPermissionsResult"
--> "buildGoogleApiClient"
--> "onResume"
    If "permission granted" then
    --> [Yes]"onConnected"
    --> "createLocationRequest"
    --> "startLocationUpdates"
    --> "onLocationChanged"
    --> "updateUI"
    --> "updateUI"
    --> "onResume"
    else
    --> [Permission Denied]"onRequestPermissionsResult"
    --> "onResume"
    else
    If "onBackPressed" then
        --> "stopLocationUpdates"
        --> "onStop"
    Endif
    Endif

@enduml
